name: 'Textile Bucket Replication on Pinata'
description: 'Textile Buckets are automatically pinned by Textile. If you want additional network replication, this will copy your Bucket to Pinata.'
inputs:
  cid:  # cid to pin
    description: 'CID output from Textile Bucket'
    required: true
  bucket: # bucket name
    description: 'Name of Textile Bucket'
    required: true
  pinata_key: 
    description: 'Pinata API Key'
    required: true
  pinata_secret: 
    description: 'Pinata API Secret'
    required: true
  pinata_name: 
    description: 'Optional name of pin request in Pinata'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
