name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        cid: 'QmPLxsffBZDY1FY36vhvsMx1Mz4qNSTdeXuMqohVEhQ4Nb'
        bucket: 'jekyll-ipfs-blog'
        pinata_key: ${{ secrets.PINATA_KEY }}
        pinata_secret: ${{ secrets.PINATA_SECRET }}
        pinata_name: 'ci-test-pin'

  integration:
    runs-on: ubuntu-latest
    name: Runs the real action
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bucket Replication
        uses: ./ # Uses an action in the root directory
        id: replicate
        with:
          cid: 'QmPLxsffBZDY1FY36vhvsMx1Mz4qNSTdeXuMqohVEhQ4Nb'
          bucket: 'jekyll-ipfs-blog'
          pinata_key: ${{ secrets.PINATA_KEY }}
          pinata_secret: ${{ secrets.PINATA_SECRET }}
          pinata_name: 'ci-test-pin'